## Сергій Долгополов

### 1. Створіть випадковий тензор форми `(7, 7)`.


In [1]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create random tensor
tensor1 = torch.rand(7, 7, device=device)
print(tensor1)

tensor([[0.3376, 0.3622, 0.7045, 0.3352, 0.1177, 0.7495, 0.7537],
        [0.4029, 0.3799, 0.0268, 0.3593, 0.7933, 0.5102, 0.2697],
        [0.6283, 0.7156, 0.7956, 0.0074, 0.6231, 0.2458, 0.0341],
        [0.2521, 0.5632, 0.6259, 0.5237, 0.8618, 0.2754, 0.3703],
        [0.0771, 0.9895, 0.0748, 0.4733, 0.2967, 0.2555, 0.9152],
        [0.1998, 0.0439, 0.8445, 0.2375, 0.6140, 0.6498, 0.2727],
        [0.6567, 0.8518, 0.8292, 0.2198, 0.9471, 0.9528, 0.6690]],
       device='cuda:0')


### 2. Виконайте матричне множенні для тензора з 1 завдання і випадкового тензора форми `(1, 7)` (за необхідності, транспонуйте другий тензор).

In [2]:
# Create another random tensor
tensor2 = torch.rand(1, 7, device=device)
# Perform matrix multiplication 
print(tensor1 @ tensor2.T)

tensor([[2.0523],
        [1.8118],
        [1.8376],
        [2.0360],
        [1.9664],
        [1.7847],
        [3.3894]], device='cuda:0')


### 3. Встановіть random seed в `0` і виконайте завдання 1 і 2 знову.

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7, device=device)
tensor2 = torch.rand(1, 7, device=device)

# Matrix multiply tensors
tensor3 = tensor1 @ tensor2.T
print(tensor3)

tensor([[2.0534],
        [2.3578],
        [1.8793],
        [1.6912],
        [2.5042],
        [2.0659],
        [1.9022]], device='cuda:0')


### 4. Знайдіть максимальне і мінімальне значення у виході 3 завдання.

In [9]:
# Find max
print(tensor3.max())
# Find min
print(tensor3.min())

tensor(2.5042, device='cuda:0')
tensor(1.6912, device='cuda:0')


### 5. Знайдіть індекси максимального і мінімального значення у виході 3 завдання.

In [ ]:
# Find arg max
print(tensor3.argmax())

# Find arg min
print(tensor3.argmin())


### 6. Створіть випадковий тензор форми `(1, 1, 1, 10)`. Потім з нього створіть новий тензор, у якого вилучено всі одиничні розмірності. При створенні тензору встановіть seed рівним `7`. Надрукуйте перший і другий тензори і їхню форму.

In [13]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor4 = torch.rand(1, 1, 1, 10, device=device)
print(tensor4)
print(tensor4.shape)
# Remove single dimensions
tensor5 = torch.squeeze(tensor4)
print(tensor5)
print(tensor5.shape)
# Print out tensors and their shapes


tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')
torch.Size([1, 1, 1, 10])
tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
torch.Size([10])
